apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movie-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
