name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main # Workflow ini akan berjalan setiap kali ada push ke branch main

jobs:
  # Job 1: Install dependencies dan jalankan pengujian
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Menentukan versi Node.js

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watchAll=false

  # Job 2: Build Docker Image (bergantung pada job test)
  build:
    runs-on: ubuntu-latest
    needs: test # Menjalankan job ini setelah job test berhasil
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t zidane061/myapp:latest -f Dockerfile .

  # Job 3: Push Docker Image (bergantung pada job build)
  push:
    runs-on: ubuntu-latest
    needs: build # Menjalankan job ini setelah job build berhasil
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push zidane061/myapp:latest
