name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main # Workflow ini akan berjalan setiap kali ada push ke branch main

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Node.js (hanya jika diperlukan oleh dependensi)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login ke Docker Hub menggunakan secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t zidane061/myapp:latest -f Dockerfile .

  # Job 2: Test Docker Image
  test:
    runs-on: ubuntu-latest
    needs: build # Menjalankan job ini setelah job build selesai
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull Docker Image yang sudah dibangun
      - name: Pull Docker Image
        run: docker pull zidane061/myapp:latest

      # Jalankan pengujian pada Docker Image
      - name: Run Tests
        run: docker run --rm zidane061/myapp:latest npm test -- --watchAll=false

  # Job 3: Push Docker Image
  push:
    runs-on: ubuntu-latest
    needs: test # Menjalankan job ini setelah job test berhasil
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Docker Image ke Docker Hub
      - name: Push Docker Image
        run: docker push zidane061/myapp:latest
